SurfsUp/Controllers/BoardsUserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SurfsUp.Data;
using SurfsUp.Models;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using System.Text.Json;
using Models;
using System.Text;
using System.Net.Http.Json;
using Models.DTOs;
using Newtonsoft.Json;
using System.Drawing.Text;
using SurfsUp.Utility;

namespace SurfsUp.Controllers
{
    public class BoardsUserController : Controller
    {
        private readonly SurfsUpContext _context;
        private readonly SurfsUpIdentityContext _identityContext;
        private readonly HttpClient _httpClient;

        public BoardsUserController(SurfsUpContext context, SurfsUpIdentityContext identityContext, HttpClient httpClient)
        {
            _context = context;
            _identityContext = identityContext;
            //_httpClient = new HttpClient()
            //{
            //    BaseAddress = new Uri("https://localhost:7277/api/")
            //};
            _httpClient = httpClient;
            _httpClient.BaseAddress = new Uri("https://localhost:7277/api/");
        }

        async Task<string> GetAsync(string call)
        {
            using HttpResponseMessage response = await _httpClient.GetAsync(call);

            response.EnsureSuccessStatusCode();
            return await response.Content.ReadAsStringAsync();
        }

        //public Task SortAndSearch(IQueryable<Board> boardList, string type, string search)
        //{
        //    //IQueryable<Board> boards = boardList;


        //    return Task.CompletedTask;
        //}

        // GET: Boards
        public async Task<IActionResult> Index(string currentFilter,
                                                string search,
                                                int? pageNumber,
                                                string type,
                                                bool rentError)
        {
            ViewData["CurrentFilter"] = search;
            ViewData["Type"] = type;

            if (rentError)
                ViewData["Locked"] = "Someone else is currently renting this Board. Please try again later.";

            if (search != null)
            {
                pageNumber = 1;
            }
            else
            {
                search = currentFilter;
            }
            string request = $"v1/boards/?search={search}&type={type}";

            if (!User.Identity.IsAuthenticated)
            {
                request = $"v2/boards/?search={search}&type={type}";
            }
            bool premium = User.Identity.IsAuthenticated;

            var jsonString = GetAsync(request).Result;
            var boards = JsonConvert.DeserializeObject<List<Board>>(jsonString);

            int pageSize = 8;
            return View(await PaginatedList<Board>.CreateAsync(boards, pageNumber ?? 1, pageSize));
        }

        // GET: BoardsUser/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Board == null)
            {
                return NotFound();
            }

            var board = await _context.Board
                .FirstOrDefaultAsync(m => m.Id == id);
            if (board == null)
            {
                return NotFound();
            }

            return View(board);
        }

        //method that compares to long values
        

        //GET MOETHOD
        public async Task<IActionResult> RentOut(int? id)
        {
            if (id == null || _context.Board == null)
            {
                return NotFound();
            }

            //var boardRequest = await _httpClient.GetFromJsonAsync("Rents", id);
            //var board = await JsonSerializer.DeserializeAsync<Board>(boardRequest);

            var board = await _context.Board.FirstOrDefaultAsync(m => m.Id == id);

            if (board == null)
            {
                return NotFound();
            }
            
            TimeSpan isTimerOver = DateTime.Now - board.LockDate;
            if (isTimerOver.TotalMinutes < 5)
            {
                return RedirectToAction(nameof(Index), new { @rentError = true });
            }
            board.LockDate = DateTime.Now;
            await _context.SaveChangesAsync();
            var rent = new Rent();
            return View(rent);
        }

        //POST METHOD
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RentOut(int id, [Bind(include: "StartRent,EndRent")] Rent rent)
        {
            //instansiere ny RentDto
            RentDto rentDto = new RentDto()
            {
                BoardId = id,
                StartRent = rent.StartRent,
                EndRent = rent.EndRent
            };

            //tilføjer bruger hvis logger ind
            if (User.Identity.IsAuthenticated)
            {
                rentDto.UserName = User.Identity.Name;
            }

            if (rent.StartRent.AddMinutes(5) < DateTime.Now)
            {
                ModelState.AddModelError("StartRent", "Start date must not be sooner than now");
            }
            if (rent.EndRent > rent.StartRent.AddDays(30))
            {
                ModelState.AddModelError("StartRent", "You can only rent boards for 30 days maximum");
            }

            if (rent.StartRent > rent.EndRent)
            {
                ModelState.AddModelError("StartRent", "Start date must be before end date");
            }
            
            if (ModelState.IsValid)
            {
                try
                {
                    //post as json.
                    var jsonPost = await _httpClient.PostAsJsonAsync("v1.0/rent", rentDto);
                }
                catch (Exception ex)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            
            return View(rentDto);
        }
        public async Task<IActionResult> GuestRentOut(int? id)
        {
            if (id == null || _context.Board == null)
            {
                return NotFound();
            }

            var board = await _context.Board.FirstOrDefaultAsync(m => m.Id == id);

            if (board == null)
            {
                return NotFound();
            }

            TimeSpan isTimerOver = DateTime.Now - board.LockDate;
            if (isTimerOver.TotalMinutes < 5)
            {
                return RedirectToAction(nameof(Index), new { @rentError = true });
            }
            board.LockDate = DateTime.Now;
            await _context.SaveChangesAsync();
            var rent = new GuestRentViewModel
            {
                Rent = new Rent(),
                Guest = new Guest()
            };
            return View(rent);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GuestRentOut(int id, [Bind(include: "Rent, Guest")] GuestRentViewModel rentVM)
        {
            //instansiere ny RentDto
            

            if (rentVM.Rent.StartRent.AddMinutes(5) < DateTime.Now)
            {
                ModelState.AddModelError("StartRent", "Start date must not be sooner than now");
            }
            if (rentVM.Rent.EndRent > rentVM.Rent.StartRent.AddDays(30))
            {
                ModelState.AddModelError("StartRent", "You can only rent boards for 30 days maximum");
            }

            if (rentVM.Rent.StartRent > rentVM.Rent.EndRent)
            {
                ModelState.AddModelError("StartRent", "Start date must be before end date");
            }
            GuestRentDto rentDto = new GuestRentDto()
            {
                BoardId = id,
                StartRent = rentVM.Rent.StartRent,
                EndRent = rentVM.Rent.EndRent,
                FirstName = rentVM.Guest.FirstName,
                LastName = rentVM.Guest.LastName,
                PhoneNumber = rentVM.Guest.PhoneNumber,
                IPAddress = HttpContext.Connection.RemoteIpAddress?.ToString()
            };

            if (ModelState.IsValid)
            {
                try
                {
                    
                    //post as json.
                    var jsonPost = await _httpClient.PostAsJsonAsync("v2/rent", rentDto);

                }
                catch (Exception ex)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }

            return View(rentVM);
        }

        private bool BoardExists(int id)
        {
          return _context.Board.Any(e => e.Id == id);
        }
    }
}

SurfsUp/Views/BoardsUser/Details.cshtml
@model SurfsUp.Models.Board

@{
    ViewData["Title"] = "Details";
}

@*<h1>Details</h1>*@


<div class="row detail-row mt-5">
    <div class="col-7">
        <img src="@Model.ImageURL" class="img-fluid" alt="Responsive image">
    </div>
    <div class="col-5">
        <h3>@Model.Name</h3>
        <p class="item-price">@Model.Price €</p>

        <h5 class="card-title">Product Specifications</h5>
        <h6 class="card-subtitle mb-2 text-muted">@Model.Type</h6>
        <table style="width:100%;">
            <tr>
                <td><b>Length</b></td>
                <td style="text-align:right;">@Model.Length</td>
            </tr>
            <tr>
                <td><b>Width</b></td>
                <td style="text-align:right;">@Model.Width</td>
            </tr>
            <tr>
                <td><b>Thickness</b></td>
                <td style="text-align:right;">@Model.Thickness</td>
            </tr>
            <tr>
                <td><b>Volume</b></td>
                <td style="text-align:right;">@Model.Volume</td>
            </tr>
            <tr>
                <td><b>Price</b></td>
                <td style="text-align:right;">@Model.Price</td>
            </tr>
            <tr>
                <td style="display:flex;align-content:start;"><b>Equipment(s)</b></td>
                @{
                    if (!String.IsNullOrEmpty(Model.Equipments))
                    {
                        <td style="text-align:right;">
                            @foreach (var items in Model.Equipments.Split(','))
                            {
                                <p style="margin:0;padding:0;">@items</p>
                            }
                        </td>
                    }
                    else
                    {
                        <td style="text-align:right;">None</td>
                    }
                }
            </tr>
        </table>
        @*    <p class="card-text"><b>Length:</b> @Model.Length</p>
        <p class="card-text"><b>Width:</b> @Model.Width</p>
        <p class="card-text"><b>Thickness:</b> @Model.Thickness</p>
        <p class="card-text"><b>Volume:</b> @Model.Volume</p>
        <p class="card-text"><b>Price:</b> @Model.Price</p>
        <p class="card-text"><b>Equipments:</b> @Model.Equipments</p>*@

        <ul class="details-btn-ul">
            <li class="nav-item detail-btn-li" style="width: 100%;text-align:center;">
                <a asp-action="RentOut" asp-route-id="@Model.Id" class="nav-link text-light bg-dark">Rent</a>
            </li>
            <li class="nav-item detail-btn-li" style="width: 100%;text-align:center;">
                <a asp-action="Index" class="nav-link text-light bg-dark">Back</a>
            </li>
        </ul>
    </div>
</div>
<div class="row mt-5 detail-row">
    <div class="col-4">
        <div class="card border-0">
            <div class="card-body">
                <h5 class="card-title">Product Specifications</h5>
                <h6 class="card-subtitle mb-2 text-muted">@Model.Type</h6>
                <p>
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
                </p>
                <a href="#" class="card-link text-dark">Lorem Link</a>
                <a href="#" class="card-link text-dark">Lorem ipsum Link</a>
            </div>
        </div>
    </div>
    <div class="col-4">
        <div class="card border-0">
            <div class="card-body">
                <h5 class="card-title">Brand</h5>
                <h6 class="card-subtitle mb-2 text-muted">@Model.Type</h6>
                <p>
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
                </p>
                <a href="#" class="card-link text-dark">Lorem Link</a>
                <a href="#" class="card-link text-dark">Lorem ipsum Link</a>
            </div>
        </div>
    </div>
    <div class="col-4">
        <div class="card border-0">
            <div class="card-body">
                <h5 class="card-title">About</h5>
                <h6 class="card-subtitle mb-2 text-muted">@Model.Type</h6>
                <p>
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
                </p>
                <a href="#" class="card-link text-dark">Lorem Link</a>
                <a href="#" class="card-link text-dark">Lorem ipsum Link</a>
            </div>
        </div>
    </div>
</div>
@*<div>*@
@*    <h4>Board</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Length)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Length)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Width)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Width)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Thickness)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Thickness)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Volume)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Volume)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Equipments)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Equipments)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageURL)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageURL)
        </dd>
    </dl>
</div>*@
<div>
</div>

SurfsUp/Views/BoardsUser/GuestRentOut.cshtml
@model Models.GuestRentViewModel

@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

<h4>Rent</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="GuestRentOut">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Rent.StartRent" class="control-label"></label>
                <input asp-for="Rent.StartRent" class="form-control" />
                <span asp-validation-for="Rent.StartRent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rent.EndRent" class="control-label"></label>
                <input asp-for="Rent.EndRent" class="form-control" />
                <span asp-validation-for="Rent.EndRent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Guest.FirstName" class="control-label"></label>
                <input asp-for="Guest.FirstName" class="form-control" />
                <span asp-validation-for="Guest.FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Guest.LastName" class="control-label"></label>
                <input asp-for="Guest.LastName" class="form-control" />
                <span asp-validation-for="Guest.LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Guest.PhoneNumber" class="control-label"></label>
                <input asp-for="Guest.PhoneNumber" class="form-control" />
                <span asp-validation-for="Guest.PhoneNumber" class="text-danger"></span>
            </div>
            <div stlye="font-size:50px;">GUEST</div>
            <div class="form-group">
                <input type="submit" value="GuestRentViewModel" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SurfsUp/Views/BoardsUser/Index.cshtml
@using System.Reflection
@using SurfsUp.Utility
@model PaginatedList<SurfsUp.Models.Board>

@{
    ViewData["Title"] = "Board Manager";
}


<div style="display:flex; justify-content:space-between; align-items:center;">
    <h1>Boards for Rent</h1>

    <form asp-controller="BoardsUser" asp-action="Index" method="get">
        <p style="margin:0;display:flex;">
            <select class="me-2 form-control" name="type">
                <option disabled selected hidden value="">Sort by</option>
                @foreach (PropertyInfo propertyInfo in typeof(Board).GetProperties())
                {
                    var propName = propertyInfo.Name.ToLower();
                    List<string> Hide = new List<string>() { "id", "imageurl", "rent" };
                    if (!Hide.Any(s => propName.Contains(s)))
                    {
                        if (@ViewData["Type"] != null && @ViewData["Type"].ToString() == @propertyInfo.Name)
                        {
                            <option selected="@ViewData["Type"]" value="@propertyInfo.Name">@propertyInfo.Name</option>
                        }
                        else
                        {
                            <option value="@propertyInfo.Name">@propertyInfo.Name</option>
                        }
                    }
                }
            </select>
            <input class="form-control" type="text" name="search" placeholder="Search Text" value="@ViewData["CurrentFilter"]" />
            <input class="btnSearch btn btn-dark" type="submit" value="Search" />
        </p>
    </form>
</div>
@{
    if (ViewData["Locked"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <b>@ViewData["Locked"]</b>
        </div>
    }
}
<div class="row" style="display:flex;flex-wrap:wrap; padding:0!important;">
    @foreach (var item in Model)
    {
        <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6">
            <div class="card" style="margin-top:15px;">
                <a asp-action="Details" asp-route-id="@item.Id" class="text-dark" style="text-decoration:none;">
                    <div class="card-header">
                        <h5 class="card-title" style="margin:0!important;"><b>@item.Name</b></h5>
                    </div>
                    @*ANIMATION*@
                    <div class="animation-div" style="height: 275px;overflow:hidden;">
                        <img class="card-img-top img-fluid image-style" src="@item.ImageURL" alt="">
                        <ul class="hidden-ul">
                            <li class="item-style"><b>Length:</b> <pro style="float:right;">@item.Length feet</pro></li>
                            <li class="item-style"><b>Thickness:</b> <pro style="float:right;">@item.Width inches</pro></li>
                            <li class="item-style"><b>Volume:</b> <pro style="float:right;">@item.Volume inches</pro></li>
                        </ul>
                    </div>
                </a>
                @*NOT MOVING*@
                <div>
                    <ul class="price-ul">
                        <li class="price-li"><b>Price: </b><pro style="float:right;">@item.Price €</pro></li>
                    </ul>
                    <div class="card-body board-btn">
                        <ul class="nav nav-pills card-header-pills" style="display: flex; justify-content:space-between;">
                            <li class="nav-item" style="width:100%; text-align:center;">
                                @{
                                    TimeSpan isTimerOver = DateTime.Now - item.LockDate;
                                    int timeLeft = 300000 - (int)isTimerOver.TotalMilliseconds;
                                    if (isTimerOver.TotalMinutes > 5)
                                    {
                                        <a asp-action="@(User.Identity.IsAuthenticated ? "RentOut" : "GuestRentOut")" asp-route-id="@item.Id" class="nav-link text-light bg-dark">Rent</a>
                                    }
                                    else
                                    {
                                        var uid = Guid.NewGuid().ToString("n");
                                        <a id="rent-btn-Hidden-@uid" asp-action="@(User.Identity.IsAuthenticated ? "RentOut" : "GuestRentOut")" asp-route-id="@item.Id" class="nav-link text-light bg-dark rentHidden">Rent</a>
                                        <div name="@timeLeft" id="loading-group-@uid" class="rentLoading">
                                            <div class="spinner-square">
                                                <div class="square-1 square"></div>
                                                <div class="square-2 square"></div>
                                                <div class="square-3 square"></div>
                                            </div>
                                            <p class="loading-text">Currently being rent...</p>
                                        </div>
                                    }
                                }
                            </li>
                        </ul>
                    </div>
                </div>
                @*NOT MOVING END*@
            </div>
        </div>
    }
</div>
@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}



<a asp-action="Index"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   asp-route-Type="@ViewData["Type"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   asp-route-Type="@ViewData["Type"]"
   class="btn btn-default @nextDisabled">
    Next
</a>

<script>
    var elementsShow = document.querySelectorAll('*[id^="rent-btn-Hidden-"]');
    var elementsHide = document.querySelectorAll('*[id^="loading-group-"]');
    var i = 0;
    elementsHide.forEach(function (element) {
        element.addEventListener("load", countDown(element, elementsShow[i], $(element).attr('name')));
        i++;
    });

    function countDown(elementHide, elementShow, elmDelay) {
        //debugger;
        setTimeout(() => {
            elementHide.style.display = "none";
            elementShow.style.display = "block";
        }, elmDelay);
    };

</script>

SurfsUp/Views/BoardsUser/RentOut.cshtml
@model SurfsUp.Models.Rent

@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

<h4>Rent</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="RentOut">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StartRent" class="control-label"></label>
                <input asp-for="StartRent" class="form-control" />
                <span asp-validation-for="StartRent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndRent" class="control-label"></label>
                <input asp-for="EndRent" class="form-control" />
                <span asp-validation-for="EndRent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Rent" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}