SurfsUp/Controllers/BoardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.ConstrainedExecution;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SurfsUp.Data;
using SurfsUp.Models;
using SurfsUp.Utility;

namespace SurfsUp.Controllers
{
    /* A way to restrict access to the controller to only users with the role of Admin. */
    [Authorize(Roles = StaticDetails.Role_User_Admin)]
    public class BoardsController : Controller
    {
        private readonly SurfsUpContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;

        public BoardsController(SurfsUpContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
        }

        

        // GET: Boards
        public async Task<IActionResult> Index(string sortOrder,
                                                string currentFilter,
                                                string search,
                                                int? pageNumber,
                                                string type)
        {
            ViewData["CurrentSort"] = sortOrder;

            if (search != null)
            {
                pageNumber = 1;
            }
            else
            {
                search = currentFilter;
            }

            var boards = from m in _context.Board
                            select m;

            /* Filtering the boards by the search string and then sorting them by the type. */
            if (!String.IsNullOrEmpty(search))
                boards = from b in boards where b.Name.ToLower()!.Contains(search.ToLower()) select b;

            if (!String.IsNullOrEmpty(type))
            {
                //PropertyDescriptor prop = TypeDescriptor.GetProperties(typeof(Board)).Find("Length", true);
                //var test2 = from b in _context.Board.ToList() orderby prop.GetValue(b) select b; //THIS WORKS
                //ReturnedList = (from b in _context.Board.ToList() orderby prop.GetValue(b) select b).ToList(); ///Works too
                boards = type.ToLower() switch
                {
                    "name" => from b in boards orderby b.Name select b,
                    "length" => from b in boards orderby b.Length select b,
                    "thickness" => from b in boards orderby b.Thickness select b,
                    "volume" => from b in boards orderby b.Volume select b,
                    "type" => from b in boards orderby b.Type select b,
                    "price" => from b in boards orderby b.Price select b,
                    "equipments" => from b in boards orderby b.Equipments select b,
                    _ => from b in boards orderby b.Name select b,
                };
            }

            int pageSize = 4;
            return View(await PaginatedList<Board>.CreateAsync(boards.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: Boards/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Board == null)
            {
                return NotFound();
            }

            var board = await _context.Board.AsNoTracking().FirstOrDefaultAsync(b => b.Id == id);
            if (board == null)
            {
                return NotFound();
            }

            return View(board);
        }

        // GET: Boards/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Boards/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Length,Width,Thickness,Volume,Type,Price,Equipments,ImageURL")] Board board, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var upload = Path.Combine(wwwRootPath, @"images\boards");
                    var extension = Path.GetExtension(file.FileName);

                    using (var fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                    {
                        await file.CopyToAsync(fileStream);
                    }
                    board.ImageURL = @"\images\boards\" + fileName + extension;
                }
                
                _context.Add(board);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(board);
        }

        // GET: Boards/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null || _context.Board == null)
            {
                return NotFound();
            }

            var board = await _context.Board.AsNoTracking().FirstOrDefaultAsync(b => b.Id == id);
            if (board == null)
            {
                return NotFound();
            }
            return View(board);
        }

        // POST: Boards/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Length,Width,Thickness,Volume,Type,Price,Equipments,ImageURL")] Board board, byte[] rowVersion)
        {
            if (id != board.Id)
            {
                return NotFound();
            }

            var boardToUpdate = await _context.Board.FirstOrDefaultAsync(m => m.Id == id);

            if (boardToUpdate == null)
            {
                Board deletedBoard = new Board();
                await TryUpdateModelAsync(deletedBoard);
                ModelState.AddModelError(string.Empty,
                    "Unable to save changes. The department was deleted by another user.");
                //ViewData["InstructorID"] = new SelectList(_context.Instructors, "ID", "FullName", deletedDepartment.InstructorID);
                return View(deletedBoard);
            }

            _context.Entry(boardToUpdate).Property("RowVersion").OriginalValue = rowVersion;

            if (await TryUpdateModelAsync<Board>(
                boardToUpdate,
                "",
                s => s.Name, s => s.Price, s => s.Length, s => s.Width, s => s.Thickness, s => s.Volume, s => s.Type, s => s.Equipments, s => s.ImageURL))
            {
                try
                {
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    var exceptionEntry = ex.Entries.Single();
                    var clientValues = (Board)exceptionEntry.Entity;
                    var databaseEntry = exceptionEntry.GetDatabaseValues();
                    if (databaseEntry == null)
                    {
                        ModelState.AddModelError(string.Empty,
                            "Unable to save changes. The department was deleted by another user.");
                    }
                    else
                    {
                        var databaseValues = (Board)databaseEntry.ToObject();

                        if (databaseValues.Name != clientValues.Name)
                        {
                            ModelState.AddModelError("Name", $"Current value: {databaseValues.Name}");
                        }
                        if (databaseValues.Price != clientValues.Price)
                        {
                            ModelState.AddModelError("Price", $"Current value: {databaseValues.Price} €");
                        }
                        if (databaseValues.Width != clientValues.Width)
                        {
                            ModelState.AddModelError("Width", $"Current value: {databaseValues.Width}");
                        }
                        if (databaseValues.Length != clientValues.Length)
                        {
                            ModelState.AddModelError("Length", $"Current value: {databaseValues.Length}");
                        }
                        if (databaseValues.Thickness != clientValues.Thickness)
                        {
                            ModelState.AddModelError("Thickness", $"Current value: {databaseValues.Thickness}");
                        }
                        if (databaseValues.Volume != clientValues.Volume)
                        {
                            ModelState.AddModelError("Volume", $"Current value: {databaseValues.Volume}");
                        }
                        if (databaseValues.Type != clientValues.Type)
                        {
                            ModelState.AddModelError("Type", $"Current value: {databaseValues.Type}");
                        }
                        if (databaseValues.Equipments != clientValues.Equipments)
                        {
                            ModelState.AddModelError("Equipments", $"Current value: {databaseValues.Equipments}");
                        }
                        if (databaseValues.ImageURL != clientValues.ImageURL)
                        {
                            ModelState.AddModelError("ImageURL", $"Current value: {databaseValues.ImageURL}");
                        }

                        ModelState.AddModelError(string.Empty, "The record you attempted to edit "

SurfsUp/Views/Boards/Create.cshtml
@model SurfsUp.Models.Board

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Board</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Length" class="control-label"></label>
                <input asp-for="Length" class="form-control" />
                <span asp-validation-for="Length" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Width" class="control-label"></label>
                <input asp-for="Width" class="form-control" />
                <span asp-validation-for="Width" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Thickness" class="control-label"></label>
                <input asp-for="Thickness" class="form-control" />
                <span asp-validation-for="Thickness" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Volume" class="control-label"></label>
                <input asp-for="Volume" class="form-control" />
                <span asp-validation-for="Volume" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" class="form-control" asp-items="Html.GetEnumSelectList<BoardType>()"></select>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Equipments" class="control-label"></label>
                <input asp-for="Equipments" class="form-control" />
                <span asp-validation-for="Equipments" class="text-danger"></span>
            </div>
            @*<div class="form-group">
            <label asp-for="Equipments" class="control-label"></label>
            <select asp-for="Equipments" class="form-control" asp-items="ViewBag.equipments"></select>
            </div>*@
@*            <div class="form-group">
                <label asp-for="Premium" class="control-label"></label>
                <input asp-for="Premium" type="checkbox"></input>
                <span asp-validation-for="Premium" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="ImageURL" class="control-label"></label>
                <input type="file" name="file" id="uploadInput" class="form-control mb-3" />
                @*<span asp-validation-for="ImageURL" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <input type="submit" onclick="return ValidateInput()" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        function ValidateInput() {
            if (document.getElementById("uploadInput").value == "") {
                Swal.fire({
                    icon: 'Error',
                    title: 'Oops...',
                    text: 'Please upload an image!',
                    footer: 'Hint: Click on the "Choose File" button',
                });
                return false;
            }
            return true;
        }
    </script>
    }

SurfsUp/Views/Boards/Delete.cshtml
@model SurfsUp.Models.Board

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>
<p class="text-danger">@ViewData["ConcurrencyErrorMessage"]</p>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Board</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Length)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Length)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Width)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Width)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Thickness)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Thickness)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Volume)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Volume)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Equipments)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Equipments)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageURL)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageURL)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="RowVersion" />
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

SurfsUp/Views/Boards/Details.cshtml
@model SurfsUp.Models.Board

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Board</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Length)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Length)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Width)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Width)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Thickness)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Thickness)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Volume)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Volume)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Equipments)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Equipments)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageURL)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageURL)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SurfsUp/Views/Boards/Edit.cshtml
@model SurfsUp.Models.Board

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Board</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="RowVersion" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Length" class="control-label"></label>
                <input asp-for="Length" class="form-control" />
                <span asp-validation-for="Length" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Width" class="control-label"></label>
                <input asp-for="Width" class="form-control" />
                <span asp-validation-for="Width" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Thickness" class="control-label"></label>
                <input asp-for="Thickness" class="form-control" />
                <span asp-validation-for="Thickness" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Volume" class="control-label"></label>
                <input asp-for="Volume" class="form-control" />
                <span asp-validation-for="Volume" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" class="form-control" asp-items="Html.GetEnumSelectList<BoardType>()"></select>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Equipments" class="control-label"></label>
                <input asp-for="Equipments" class="form-control" />
                <span asp-validation-for="Equipments" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="Equipments" class="control-label"></label>
                <select asp-for="Equipments" class="form-control" asp-items="ViewBag.equipments"></select>
            </div>*@
@*            <div class="form-group">
                <label asp-for="Premium" class="control-label"></label>
                <input asp-for="Premium" type="checkbox" value="true" />
                <span asp-validation-for="Premium" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="ImageURL" class="control-label"></label>
                <input asp-for="ImageURL" class="form-control" />
                <span asp-validation-for="ImageURL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

SurfsUp/Views/Boards/Index.cshtml
@using System.Reflection
@using SurfsUp.Utility
@model PaginatedList<SurfsUp.Models.Board>

@{
    ViewData["Title"] = "Board Manager";
}

<h1>Board Manager</h1>
<div style="display:flex; justify-content:space-between; align-items:center;">
    <p style="margin:0;">
        <a asp-action="Create" class="nav-link text-light bg-dark" style="border-radius:5px; width: 150px;">Add New Board</a>
    </p>
    <form asp-controller="Boards" asp-action="Index" method="get">
        <p style="margin:0;display:flex;">
            <select class="me-2 form-control" name="type">
                <option value="">All Types</option>
                @foreach (PropertyInfo propertyInfo in typeof(Board).GetProperties())
                {
                    var propName = propertyInfo.Name.ToLower();
                    List<string> Hide = new List<string>() { "id", "imageurl", "rent" };
                    if (!Hide.Any(s => propName.Contains(s)))
                    {
                        <option value="@propName">@propertyInfo.Name</option>
                    }
                }
            </select>
            <input class="form-control" type="text" name="search" placeholder="Search Text" />
            <input class="btnSearch btn btn-dark" type="submit" value="Search" />
        </p>
    </form>
</div>

<div class="row" style="display:flex;flex-wrap:wrap; padding:0!important;">

    @foreach (var item in Model)
    {
        <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6">
            <div class="card" style="margin-top:15px;">
                <div class="card-header">
                    <h5 class="card-title" style="margin:0!important;"><b>@item.Name</b></h5>
                </div>
                <img style="height: 275px; margin:20px auto 20px auto;" class="card-img-top img-fluid" src="@item.ImageURL" alt="">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><b>Length:</b> <pro style="float:right;">@item.Length feet</pro></li>
                    <li class="list-group-item"><b>Width:</b> <pro style="float:right;">@item.Width inches</pro></li>
                    <li class="list-group-item"><b>Thickness:</b> <pro style="float:right;">@item.Thickness inches</pro></li>
                    <li class="list-group-item"><b>Volume:</b> <pro style="float:right;">@item.Volume L</pro></li>
                    <li class="list-group-item"><b>Type:</b> <pro style="float:right;">@item.Type</pro></li>
                    <li class="list-group-item">
                        <b>Equipments: </b>
                        <pro style="float:right;">
                            <div style="text-align:right;">
                                @if (!String.IsNullOrEmpty(item.Equipments))
                                    @foreach (var items in item.Equipments.Split(','))
                                    {
                                        <p style="padding:0;margin:0;">@items</p>
                                    }
                                else {
                                    <p style="padding:0;margin:0;">None</p>
                                }
                            </div>
                        </pro>
                    </li>
                    <li class="list-group-item"><b>Price: </b><pro style="float:right;">@item.Price €</pro></li>

                </ul>
                <div class="card-body">
                    <ul class="nav nav-pills card-header-pills" style="display: flex; justify-content:space-between;">
                        <li class="nav-item">
                            <a asp-action="Edit" asp-route-id="@item.Id" class="nav-link text-light bg-dark">Edit</a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Details" asp-route-id="@item.Id" class="nav-link text-light bg-dark">Details</a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Delete" asp-route-id="@item.Id" class="nav-link text-light bg-dark">Delete</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    }
</div>
@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>
@*<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Length)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Width)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Thickness)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Volume)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Equipments)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Length)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Width)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Thickness)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Volume)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Equipments)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
*@